drop table ORDER_TABLE;
drop table CUSTOMER;

create table CUSTOMER (
    ID NUMERIC(10) PRIMARY KEY,
    NAME VARCHAR(256),
    VORNAME VARCHAR(256)
    WERBESPERRE BOOLEAN 
    FAMILIENSTAND 
    
);

create table ORDER_TABLE (
    ORDER_ID NUMERIC PRIMARY KEY,
    SHIPPING_ADDRESS VARCHAR(500),
    CUSTOMER_ID NUMERIC(10),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID)
);